#!/usr/bin/env bash
# Ayra - UserBot
# Copyright (C) 2021-2022 Kynan
#
# This file is a part of < https://github.com/naya1503/Ayra/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/TeamUltroid/Ultroid/blob/main/LICENSE/>.


echo "
            █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
            █░░╦─╦╔╗╦─╔╗╔╗╔╦╗╔╗░░█
            █░░║║║╠─║─║─║║║║║╠─░░█
            █░░╚╩╝╚╝╚╝╚╝╚╝╩─╩╚╝░░█
            █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█

      

"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi

if [ $SESSION1 ] ; then
  wget https://gist.githubusercontent.com/asaaqa/49a74bbcc13e6f1e563223b4fc421212/raw/f108e525fa95fa7b1af8a37b79059d1e2a2c1f74/main.py && \
  python3 app.py && \
  python3 main.py
else
  python3 app.py && \
  python3 -m Ayra
fi
